#pragma once

#include "port/hooks/impl/EventSystem.h"

#define DISPLAY_UPDATE_EVENT_PRE  INTERNAL_EVENT_ID(1, EVENT_TYPE_PRE)
#define DISPLAY_UPDATE_EVENT_POST INTERNAL_EVENT_ID(1, EVENT_TYPE_POST)

#define GAME_UPDATE_EVENT_PRE  INTERNAL_EVENT_ID(2, EVENT_TYPE_PRE)
#define GAME_UPDATE_EVENT_POST INTERNAL_EVENT_ID(2, EVENT_TYPE_POST)