#pragma once

#ifdef __cplusplus
extern "C" {
#endif

void PortEnhancements_Register();
void PortEnhancements_Init();
void PortEnhancements_Exit();
#define SETUPDL_OPTIONAL(digits) \
    (CVarGetInteger("gHUDPointFiltering", 1) == 1 ? SETUPDL_##digits##_POINT : SETUPDL_##digits)

#define SETUPDL_29_OPTIONAL SETUPDL_OPTIONAL(29)
#define SETUPDL_36_OPTIONAL SETUPDL_OPTIONAL(36)
#define SETUPDL_62_OPTIONAL SETUPDL_OPTIONAL(62)
#define SETUPDL_63_OPTIONAL SETUPDL_OPTIONAL(63)
#define SETUPDL_67_OPTIONAL SETUPDL_OPTIONAL(67)
#define SETUPDL_75_OPTIONAL SETUPDL_OPTIONAL(75)
#define SETUPDL_76_OPTIONAL SETUPDL_OPTIONAL(76)
#define SETUPDL_77_OPTIONAL SETUPDL_OPTIONAL(77)
#define SETUPDL_78_OPTIONAL SETUPDL_OPTIONAL(78)
#define SETUPDL_81_OPTIONAL SETUPDL_OPTIONAL(81)
#define SETUPDL_83_OPTIONAL SETUPDL_OPTIONAL(83)
#define SETUPDL_85_OPTIONAL SETUPDL_OPTIONAL(85)

#ifdef __cplusplus
};
#endif